title: Kotlin SCP
email: your-email@example.com
description: >-
  Kotlin Guide - Mobile Application Secure Coding Practices, is a guide written
  for anyone using Kotlin for mobile development.
baseurl: "Kotlin-SCP/"
url: ""
twitter_username: Checkmarx
github_username:  Checkmarx

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-readme-index
