title: Kotlin SCP
email: your-email@example.com
description: >-
  Kotlin Secure Coding Practices Quick Reference Guide.
baseurl: ""
url: ""
twitter_username: Checkmarx
github_username:  Checkmarx

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-readme-index
