version: "3.7"
services:
  build:
    build: .
    image: kotlin-scp:latest
    entrypoint: bash -c "npm i && node_modules/.bin/gitbook install && npm run build; rm -rf node_modules"
    network_mode: host
    volumes:
      - .:/build

